#!/usr/bin/env python3
"""
Q11 Freedom - generates frontend/src/lib/ouiData.ts (vendor by MAC prefix).

It only includes consumer brands that help recognize a device at home: the
full list (~40k prefixes) would weigh ~1 MB and the router has little space.

Usage:
  curl -sL -o /tmp/manuf https://www.wireshark.org/download/automated/data/manuf
  python3 scripts/gen-oui.py /tmp/manuf
"""
import re
import sys
from pathlib import Path

# (displayed brand, regex over the registered name, suggested type or '')
# types: phone computer console tv iot camera printer router  ('' = infer from the name)
# 'oem' = WiFi module maker: it does not tell what the device is.
BRANDS = [
    ('Apple', r'^Apple, Inc', ''),
    ('Samsung', r'^Samsung Electronics|^SAMSUNG ELECTRO', ''),
    ('Xiaomi', r'Xiaomi', ''),
    ('Huawei', r'^Huawei', ''),
    ('Honor', r'^Honor Device', 'phone'),
    ('Motorola', r'^Motorola Mobility', ''),
    ('Google', r'^Google, Inc', ''),
    ('OnePlus', r'OnePlus', 'phone'),
    ('Oppo', r'GUANGDONG OPPO', 'phone'),
    ('Vivo', r'vivo Mobile', 'phone'),
    ('Realme', r'Realme Chongqing', 'phone'),
    ('LG', r'^LG Electronics', ''),
    ('Sony', r'^Sony Corporation|^Sony Mobile', ''),
    ('PlayStation', r'^Sony Interactive', 'console'),
    ('Nintendo', r'^Nintendo', 'console'),
    ('Microsoft', r'^Microsoft', 'computer'),
    ('Amazon', r'^Amazon Technologies', 'iot'),
    ('Roku', r'^Roku', 'tv'),
    ('TCL', r'^TCL King|^TCL Technoly', 'tv'),
    ('Hisense', r'Hisense', 'tv'),
    ('Vizio', r'^VIZIO', 'tv'),
    ('Wyze', r'^Wyze Labs', 'camera'),
    ('Hikvision', r'Hikvision', 'camera'),
    ('Dahua', r'Dahua Technology', 'camera'),
    ('EZVIZ', r'EZVIZ', 'camera'),
    ('Ring', r'^Ring LLC', 'camera'),
    ('Arlo', r'^Arlo Technolog', 'camera'),
    ('HP', r'^Hewlett Packard$|^HP Inc', ''),
    ('Epson', r'^Seiko Epson', 'printer'),
    ('Canon', r'^Canon Inc', 'printer'),
    ('Brother', r'^Brother Industries', 'printer'),
    ('TP-Link', r'^TP-Link|^TP-LINK', ''),
    ('Tuya', r'Tuya', 'iot'),
    ('Espressif', r'^Espressif', 'iot'),
    ('Sonos', r'^Sonos', 'iot'),
    ('Philips Hue', r'^Signify|^Philips Lighting', 'iot'),
    ('Nest', r'^Nest Labs', 'iot'),
    ('Belkin', r'^Belkin', 'iot'),
    ('BroadLink', r'BroadLink', 'iot'),
    ('Shelly', r'^Allterco', 'iot'),
    ('Raspberry Pi', r'^Raspberry Pi', 'iot'),
    ('Ubiquiti', r'^Ubiquiti', 'router'),
    ('Netgear', r'^NETGEAR', 'router'),
    ('D-Link', r'^D-Link', 'router'),
    ('ASUS', r'^ASUSTek', ''),
    ('Lenovo', r'^Lenovo|^LCFC', 'computer'),
    ('Dell', r'^Dell Inc', 'computer'),
    ('Intel', r'^Intel Corporate', 'computer'),
    # WiFi module makers: shown, but they do not identify the device
    ('Fn-Link', r'Fn-Link|FN-LINK', 'oem'),
    ('Earda', r'^Earda', 'oem'),
    ('Foxconn', r'^Cloud Network Technology|^Hon Hai', 'oem'),
    ('AzureWave', r'^AzureWave', 'oem'),
    ('Murata', r'^Murata', 'oem'),
    ('Realtek', r'^Realtek', 'oem'),
    ('MediaTek', r'^MediaTek', 'oem'),
    ('Liteon', r'^Liteon|^LITE-ON', 'oem'),
    ('USI', r'^Universal Global Scientific', 'oem'),
]


def main(manuf_path: str) -> None:
    rx = [(b, re.compile(r), t) for b, r, t in BRANDS]
    groups: dict[str, list[str]] = {b: [] for b, _, _ in BRANDS}
    for line in Path(manuf_path).read_text(encoding='utf-8').splitlines():
        if not line or line.startswith('#'):
            continue
        parts = [p.strip() for p in line.split('\t')]
        if len(parts) < 3 or len(parts[0]) != 8:   # 24-bit prefixes only
            continue
        oui, long_name = parts[0].replace(':', '').upper(), parts[2]
        for brand, r, _ in rx:
            if r.search(long_name):
                groups[brand].append(oui)
                break

    types = {b: t for b, _, t in BRANDS}
    rows = [(b, sorted(o)) for b, o in groups.items() if o]
    out = [
        '/* Generated by scripts/gen-oui.py from the Wireshark "manuf" file. Do not edit by hand. */',
        '// [brand, suggested type ("" = infer from the name, "oem" = generic WiFi module), prefixes]',
        'export const OUI_BRANDS: [string, string, string][] = [',
    ]
    out += [f"  [{b!r}, {types[b]!r}, '{' '.join(o)}']," for b, o in rows]
    out.append('];')
    dest = Path(__file__).resolve().parent.parent / 'frontend/src/lib/ouiData.ts'
    dest.write_text('\n'.join(out) + '\n', encoding='utf-8')
    total = sum(len(o) for _, o in rows)
    print(f'{dest.name}: {len(rows)} brands, {total} prefixes, {dest.stat().st_size // 1024} KB')


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else '/tmp/manuf')
